"""empty message

Revision ID: 188de4c64020
Revises: 
Create Date: 2025-04-15 16:46:37.360507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188de4c64020'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_email'), ['email'], unique=True)

    op.create_table('level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_email'), ['email'], unique=True)

    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('module_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_email'), ['email'], unique=True)

    op.create_table('fee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('UNPAID', 'PAID', 'OVERDUE', 'CANCELLED', name='fee_status_enum'), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_status'), ['status'], unique=False)

    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_level_id'), ['level_id'], unique=False)

    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semester_level_id'), ['level_id'], unique=False)

    op.create_table('level_module_association',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('level_id', 'module_id')
    )
    with op.batch_alter_table('level_module_association', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_level_module_association_level_id'), ['level_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_level_module_association_module_id'), ['module_id'], unique=False)

    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weeks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_semester_id'), ['semester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('docs_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_level_id'), ['level_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_parent_id'), ['parent_id'], unique=False)

    op.create_table('teacher_group_association',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'group_id')
    )
    with op.batch_alter_table('teacher_group_association', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_group_association_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_group_association_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('absence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('justified', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'session_id', name='_student_session_uc')
    )
    with op.batch_alter_table('absence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_absence_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_absence_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_absence_student_id'))
        batch_op.drop_index(batch_op.f('ix_absence_session_id'))

    op.drop_table('absence')
    with op.batch_alter_table('teacher_group_association', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_group_association_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_group_association_group_id'))

    op.drop_table('teacher_group_association')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_parent_id'))
        batch_op.drop_index(batch_op.f('ix_student_level_id'))
        batch_op.drop_index(batch_op.f('ix_student_group_id'))
        batch_op.drop_index(batch_op.f('ix_student_email'))

    op.drop_table('student')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_session_start_time'))
        batch_op.drop_index(batch_op.f('ix_session_semester_id'))
        batch_op.drop_index(batch_op.f('ix_session_module_id'))
        batch_op.drop_index(batch_op.f('ix_session_group_id'))

    op.drop_table('session')
    with op.batch_alter_table('level_module_association', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_level_module_association_module_id'))
        batch_op.drop_index(batch_op.f('ix_level_module_association_level_id'))

    op.drop_table('level_module_association')
    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semester_level_id'))

    op.drop_table('semester')
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_teacher_id'))

    op.drop_table('module')
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_level_id'))

    op.drop_table('group')
    with op.batch_alter_table('fee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_status'))
        batch_op.drop_index(batch_op.f('ix_fee_parent_id'))

    op.drop_table('fee')
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_email'))

    op.drop_table('teacher')
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_email'))

    op.drop_table('parent')
    op.drop_table('level')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_email'))

    op.drop_table('admin')
    # ### end Alembic commands ###
