"""initial migration

Revision ID: 36b6e40eec2b
Revises: 
Create Date: 2025-03-15 19:46:25.924864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b6e40eec2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('firstName', sa.String(length=50), nullable=True),
    sa.Column('lastName', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('isEmailVerified', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('phoneNumber', sa.String(length=20), nullable=False),
    sa.Column('isPhoneVerified', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('profilePicture', sa.String(length=255), nullable=True),
    sa.Column('birthDate', sa.Date(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergencyContact', sa.String(length=50), nullable=True),
    sa.Column('hasPaidFees', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parentId', sa.Integer(), nullable=False),
    sa.Column('otpCode', sa.String(length=10), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('isUsed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parentId'], ['parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('requestedLevel', sa.String(length=50), nullable=True),
    sa.Column('requestedYear', sa.Integer(), nullable=True),
    sa.Column('isApproved', sa.Boolean(), nullable=True),
    sa.Column('requestDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('classroom', sa.String(length=50), nullable=True),
    sa.Column('isEnrolled', sa.Boolean(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('pending_student')
    op.drop_table('otp')
    op.drop_table('teacher')
    op.drop_table('parent')
    op.drop_table('user')
    # ### end Alembic commands ###
